### ISSUE TITLE
EAV support for Postgres

### ISSUE THREAD

**Issue by bgsouza** [hanami/hanami#1026]
Has anyone here used the EAV model on postgres inside Hanami?
I'm having trouble executing "CREATE TABLE <table> PARTITION OF <parent-table> FROM VALUES (..) to (..)"
I can't execute this raw query and no ORM or gem (pg_party, pg_partition_manager) helped

**Comment by cllns** [comment]
I'm not really sure what your use-case is, or if this is a Hanami-specific problem since you said you can't execute the raw query.

If this is a Hanami issue, can you open an issue in https://github.com/hanami/model with a lot of detail about what you're doing and trying to achieve? A reproducible example, with what Postgres version you're using, on the most recent stable version of hanami-model would be ideal. From a brief google search, it looks like JSON/JSONB columns are preferred over the EAV pattern nowadays.

**Comment by bgsouza** [comment]
Hi @cllns, I was trying to look for ways to execute this raw query. I even tried with 'repository.read ()', but it obviously didn't work
I changed my strategy, now I am using an out-of-scope hanami consumer who is solely responsible for performing partition creation
