### ISSUE TITLE
Gemfiles tracking hanami-view GitHub repo should rename master branch to 1.x-master (was: `bundle install` failed)

### ISSUE THREAD

**Issue by k0va1** [hanami/hanami#1036]
Hi! I've tried to pull the project and install gems and I've got an error:
```Fetching https://github.com/hanami/view.git
The dependency jdbc-sqlite3 (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency therubyrhino (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'hanami-view (~> 1.3)' in https://github.com/hanami/view.git (at
master@c2c6243).
The source contains 'hanami-view' at: 0.7.0
```

So hanami-view version has to be upgraded to `1.x-master` in Gemfile

**Comment by jodosha** [comment]
@k0va1 Do you mean that you tried to git clone `hanami/hanami` repository from GitHub and you run into this error?

**Comment by k0va1** [comment]
@k0va1 yep, exactly. In `master` branch

**Comment by cllns** [comment]
@k0va1, you can fix this by changing your Gemfile branch for `hanami-view` from `master` to `1.x-master`. That might be the solution we implement here too, but @timriley will know better.

```diff
-gem 'hanami-view',        '~> 1.3', require: false, git: 'https://github.com/hanami/view.git',        branch: 'master'
+gem 'hanami-view',        '~> 1.3', require: false, git: 'https://github.com/hanami/view.git',        branch: '1.x-master'
```

**Comment by timriley** [comment]
Hi @k0va1, it looks like you figured out the right fix in your original issue description:

**Anyone previously tracking the `master` branch in their application's `Gemfile` should change the branch to `1.x-master`.**

---

Now, for some extra context: the dry-view gem is in the process of being renamed to hanami-view. In order to keep both gems’ independent git histories, we've imported dry-view's own `master` branch and its history, and renamed the _previous_ hanami-view `master` branch to `1.x-master`.

This means you can e.g. still pin to particular commits from the hanami-view gem, since nothing has been erased, but you'll just have to make sure you reference the `1.x-master` instead of `master` if you want that version of the gem.

In making this change, I figured that there would probably be only a small number of projects using tracking hanami-view master in their Gemfiles, especially given the gem has been changing relatively slowly in recent times. And I also figured that anyone who chooses to track `master` should be willing to tolerate the little bit of adjustment work to keep things running :)

**Comment by jodosha** [comment]
@timriley @cllns I believe @k0va1 tried to clone this repository for an OSS contribution.

---

If you checkout the latest commit in `master` branch (`b68ab00`) and run `bundle update`, you will be able to reproduce the problem.

```shell
$ bundle update
Fetching https://github.com/hanami/utils.git
Fetching https://github.com/hanami/validations.git
Fetching https://github.com/hanami/router.git
Fetching https://github.com/hanami/controller.git
Fetching https://github.com/hanami/view.git
Fetching https://github.com/hanami/model.git
Fetching https://github.com/hanami/helpers.git
Fetching https://github.com/hanami/mailer.git
Fetching https://github.com/hanami/assets.git
Fetching https://github.com/hanami/devtools.git
Fetching https://github.com/hanami/webconsole.git
The dependency jdbc-sqlite3 (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'hanami-view (~> 1.3)' in https://github.com/hanami/view.git (at master@c2c6243) or in gems cached in vendor/cache.
The source contains 'hanami-view' at: 0.7.0
```

**Comment by timriley** [comment]
OK, thanks for clarifying this.

To test, I've just done this:

```
git clone https://github.com/hanami/view.git view-fresh-checkout
cd view-fresh-checkout
bundle
bundle exec rake
bundle update
bundle exec rake
```

The checked out branch is `1.x-master`. There are no errors, all the tests pass, and `bundle info hanami-view` is reporting version 1.3.3 is being used.

To me, this looks like everything is fine?

**Comment by cllns** [comment]
@timriley Should we also update the `Gemfile` for this project? https://github.com/hanami/hanami/blob/master/Gemfile#L15 to use `1.x-master`?

**Comment by timriley** [comment]
@cllns Ah! Yeah, I think that's the clincher! I'll adjust that in a moment.
