### ISSUE TITLE
Cannot create new hanami application

### ISSUE THREAD

**Issue by turbod** [hanami/hanami#1108]
Hi,
I run the following command:
`hanami new bookshelf `

and I get this exception

`/home/username/.rvm/gems/ruby-3.0.1/gems/dry-types-0.12.3/lib/dry/types/definition.rb:33:in initialize: wrong number of arguments (given 3, expected 1..2) (ArgumentError)  `

Can anyone help, how can I fix this?

**Comment by jodosha** [comment]
@turbod Hanami 1 isn't compatible with Ruby 3, you should use Ruby 2.7 for that.

We're working on Hanami 2, which is compatible with Ruby 2 and 3.

**Comment by turbod** [comment]
thx

**Comment by sreeram-venkitesh** [comment]
@jodosha I had faced this same issue when I was trying out Hanami by following the commands from the [install](https://hanamirb.org/#install) section in the Hanami homepage. I was using Ruby `3.0.2` and had to search through the issues in GitHub to learn that Ruby 3 is not supported as of now in Hanami 1. Do you think it'd make sense to add this as a small message in the homepage, along with the instructions in the install section so that the experience is smooth? First time users might dive right in and install the gem before starting to go through the documentation in detail, right? 

I'll be happy to send a PR for this. Please let me know what you think!

**Comment by cllns** [comment]
@sreeram-venkitesh Thanks for the push on this. You're right it's a terrible experience. I just added a note to the homepage. https://hanamirb.org/
