### ISSUE TITLE
Registering custom middleware in a way that's visible in `hanami middleware`

### ISSUE THREAD

**Issue by janko** [hanami/hanami#1250]
hkIn order to test out Hanami 2, I'm trying to set up a blog that uses Rodauth. I have `config/providers/sequel.rb` which sets up a Sequel database:

```rb
# config/providers/sequel.rb
Hanami.app.register_provider(:sequel) do
  prepare do
    require "sequel"
  end

  start do
    register "db", Sequel.connect(target["settings"].database_url)
  end

  stop do
    target["db"].disconnect
  end
end
```

And I have `app/rodauth_app.rb` which defines the Rodauth app:

```rb
# app/rodauth_app.rb
module Blog
  class RodauthApp < Roda
    plugin :middleware
    plugin :rodauth do
      # ...
    end
  end
end
```

The Rodauth app has to be loaded after the Sequel provider has booted, because configuring Rodauth will fail if there is no Sequel database connection. In order to help with that, I decided to create a wrapper middleware, which can be added to the stack without immediately loading the Rodauth app.

```rb
# app/rodauth_middleware.rb
module Blog
  class RodauthMiddleware
    def initialize(app)
      @app = app
    end

    def call(env)
      Blog::RodauthApp.new(@app).call(env)
    end
  end
end
```

Where is the best place to add `Blog::RodauthMiddleware` to the middleware stack? I tried `config/app.rb`, but autoloading isn't set up at that point yet:

```rb
# config/app.rb
require "hanami"

module Blog
  class App < Hanami::App
    config.middleware.use Blog::RodauthMiddleware
  end
end
```

I then tried moving the middleware definition to `lib/blog/rodauth_middleware.rb` instead, and requiring `blog/rodauth_middleware`, but that doesn't work, presumably because the load path isn't set up at that point yet.

Next I tried moving it into `config/providers/rodauth.rb`, which worked:

```rb
# config/providers/rodauth.rb
Hanami.app.register_provider(:rodauth) do
  start do
    Hanami.app.config.middleware.use Blog::RodauthMiddleware
  end
end
```

However, it doesn't show up in `hanami middleware`, presumably because that command doesn't boot the application. Is there a recommended way to do this so that it's listed in the list of middlewares?

**Comment by jodosha** [comment]
@janko Thanks for checking Hanami 2.

`config/app.rb` is the place where to mount your Rack middleware.
Specifically:

```ruby
# config/app.rb
require "hanami"

module Blog
  class App < Hanami::App
    config.middleware.use Blog::RodauthMiddleware
  end
end
```

I assume that `Blog::RodauthMiddleware` isn't autoloaded by Zeitwerk because of namespace conventions, could you please try to move `app/rodauth_app.rb` to `lib/blog/rodauth_app.rb`?

**Comment by janko** [comment]
Thanks, I did mention that I tried to move it to `lib/blog/rodauth_app.rb`, but still got `NameError: uninitialized constant Blog::RodauthMiddleware` (adding a `require "blog/rodauth_app"` didn't work either).

**Comment by jodosha** [comment]
@timriley or @solnic could you please have a look? I'm not that skilled with Zeitwerk setup. Thanks 🙏

**Comment by janko** [comment]
It seems that Zeitwerk is setup only at boot time, not on subclassing `Hanami::App`. I'm guessing the reason is to allow modifying dry-system's Zeitwerk setup via app config.

Not sure if there is an easy way to have the middleware in a separate file. I'm fine with requiring it manually from `lib`, so if at least the load path is updated on subclassing `Hanami::App`. I would just like to avoid `require_relative` if possible.

**Comment by solnic** [comment]
@janko any chance you could push a repo with this setup to GH so that I could take a look and make it work? Middlewares are kinda odd citizens because they receive the entire rack app as their constructor argument. I wanted the whole routing/rack layer to be bootable via provider but, at least for now, it was too hard for us to achieve it so it's one of the "special things" that the framework handles when it's booting.

**Comment by timriley** [comment]
@janko You're right about the reasons for Zeitwerk not being ready until App.prepare. I'll revisit our $LOAD_PATH setup with your use case in mind. Sometime in the next 24h.

**Comment by timriley** [comment]
@janko So right now we push `/lib/` onto `$LOAD_PATH` in the `Hanami::App.inherited` hook.

This means the following should work for you:

```ruby
# frozen_string_literal: true

require "hanami"

module Blog
  class App < Hanami::App
    # Will successfully require the file at lib/blog/rodauth_middleware.rb
    require "blog/rodauth_middlewware"
    config.middleware.use RodauthMiddleware
  end
end
```

I've tested on a newly created Hanami app and it works fine. I'd recommend you do this to unblock you and help you continue testing (thank you so much for testing things! ❤️)

That you came across this hitch does make me wonder if there's more we can do here to make things less surprising for users. A couple of things come to mind:

- We could create a top-level Zeitwerk "lib loader" (_outside_ of the Hanami app) and configure it _just_ to autoload from `lib/[app_name]`. We could do this as part of `Hanami.setup` so that it's ready by the time `config/app.rb` is loaded.
- Perhaps a little simpler, we could update `Hanami.setup` so it pushes `/lib/` onto the `$LOAD_PATH`. This way you could do a conventional `require` at the top of the file rather than inside the app class.
- Or both!

**Comment by timriley** [comment]
Ah, the trick with Zeitwerk setup at this stage is that we don't know what `[app_name]` is until we've required `config/app.rb` and the app class is registered.

We could potentially just set up Zeitwerk for the entirety of lib/, which I'll do a quick spoke on now.

**Comment by timriley** [comment]
Ah yes, and the autoloader should really respect custom inflections specified in the app config.

So given this, I think we should probably just move the $LOAD_PATH setup only, and not do anything with autoloading outside of the app class.

**Comment by janko** [comment]
Amazing, appreciate the quick fix, it's working great 🤘🏻

**Comment by timriley** [comment]
Thanks for checking it, @janko!

**Comment by janko** [comment]
Completed a simple JSON API application that uses Rodauth, for those interested – https://github.com/janko/hanami-rodauth-example 🙂 

I didn't come across any additional hurdles on the way, great job with the whole developer experience 👏🏻
