### ISSUE TITLE
We can't set custom middleware in slice config.

### ISSUE THREAD

**Issue by MasanoriOnishi** [hanami/hanami#1278]
```
module TestApp
  module Middlewares
    class Core
      def initialize(app)
        @app = app
      end
    end

    class Prepare < Core
      def call(env)
        env["tested"] = []
        @app.call(env)
      end
    end

    class AppendOne < Core
      def call(env)
        env["tested"] << "one"
        @app.call(env)
      end
    end

    class AppendTwo < Core
      def call(env)
        env["tested"] << "two"
        @app.call(env)
      end
    end
  end
end
```

```
module TestApp
  class Slice < Hanami::Slice
    config.middleware.use TestApp::Middlewares::Prepare
    config.middleware.use TestApp::Middlewares::AppendOne
  end
end
```

I found that even if I wrote the above, the middleware would not run.
I think it should work.

```
module AppPrototype
  class App < Hanami::App
    config.middleware.use AppPrototype::Middlewares::Prepare
    config.middleware.use AppPrototype::Middlewares::AppendOne
  end
end
```
On the other hand, the above works well.

**Comment by timriley** [comment]
Thanks for this report. This is a known limitation with middleware config: middleware to be used by the app's router can only be configured on the app, not on individual slices.

To better understand it, consider it this way: the router you use in an ordinary Hanami app comes from your `Hanami::App` subclass. If you want config-based middleware to be used in that router, you need to configure it in the same place that creates the router: the app.

However, you can insert middleware for a slice's routes directly in your config/routes.rb file. This isn't documented right now (we should change that!) but it is intentional and supported:

```ruby
```
