### ISSUE TITLE
Hanami versus Rails (long term objective: see the reddit discussion and entry, in the body of this issue request

### ISSUE THREAD

**Issue by rubyFeedback** [hanami/hanami#1381]
Recently there was this discussion on reddit:

https://old.reddit.com/r/ruby/comments/1cbxpy1/should_you_use_ruby_on_rails_or_hanami/

The article was:

https://blog.appsignal.com/2024/04/24/should-you-use-ruby-on-rails-or-hanami.html

So, here, I am not so much interested in the article or discussion on reddit. But, instead ... where does Hanami stand?

Not only in regards to sinatra, padrino or rails, but more generally.

I always felt the sinatra way much easier to combine and integrate; and rails too opinionated and heavy. I also don't want to be forced into MVC (not that I hate it, but I also don't want to slavishly have to adapt to it).

I wanted something a bit better than sinatra but not quite as heavy as rails.

Hanami also follows the MVC pattern, but what if Hanami itself could become more flexible overall? Aka a bit more like sinatra (but more advanced), without becoming a rails 2.0 emulation?

I am not quite sure what the point of this issue request here is, so it is fine to close it. The more important part is to think whether Hanami could be a bit more general-purpose, like sinatra, but offering more features than sinatra (including more "batteries included" too).

**Comment by wuarmin** [comment]
Hanami offers great flexibility. I can't think of another Ruby app where I wouldn't use Hanami. Whether it's a web app or something else, it doesn't matter. It shines in every area. The performance is great and Hanami leads to a straightforward design. 

You just have to start with it, then you will see how much fun it is to work with Hanami.

**Comment by krzykamil** [comment]
I haven't been using Hanami for long and I mostly started, cause I found myself using dry-rb libraries in all my professional projects whenever possible. Their mix of functional programming with ruby just always spoke to me. Hanami being based on those libs, just seemed like an obvious thing to try out for me.

It offers a lot of the same that Rails does (MVC), but with vastly different approaches. Same same, but different as they say.

So far what I really like about it, is it's focus on being explicit, specially when it comes to dependencies and providers. Sure, you can do something simliar in Rails, since RoR is surprisingly flexible too, but Hanami comes with that packaged. DDD is possible in Rails, but often not convienent. Hanami is better at enforcing certain code style, yet remains flexible in a lot of other spaces. 

Yes it is slower to build even simple stuff in Hanami, compared to Rails, but to be honest, in web development it is almost impossible to compete with Rails in building stuff fast. It is too convenient. Hanami does not have that, but it does not try to compete with Rails. It offers a different set of tools altogether.

If you know elixir and phoenix, building stuff with Hanami is sort of a bridge between RoR and Phoenix. Learning elixir knowing just ruby is super hard. Learning elixir (and functional programming), knowing ruby while using dry-rb and hanami, comes more naturally (to me at least).

I haven't had a chance to work on a professional project in Hanami yet, but I do something in it in my pet projects most days of the week and see a lot of potential in it. Besides, it is just fun :)

**Comment by timriley** [comment]
@wuarmin and @krzykamil, thank you for responding here with your helpful words 😍

@rubyFeedback — this is the second vague and unactionable issue you've filed inside this repo. Please do not do this again; issues on GitHub are for legitimate software bugs only. If you'd like to ask questions and engage with the Hanami community, [use our forum](https://discourse.hanamirb.org).
