### ISSUE TITLE
Inside providers, add a `slice` alias for `target`

### ISSUE THREAD

**Issue by alassek** [hanami/hanami#1417]

**Comment by timriley** [comment]
@alassek Some thoughts here, in case they help you:

I was expecting that this would mostly be dry-system work. Possibly allowing a custom provider class to be configured. This would allow Hanami to then configure one that provides a `#slice` method that serves as an alias for `target_container`.

In fact, I wonder if this change could obviate some or all of https://github.com/dry-rb/dry-system/pull/270 and https://github.com/hanami/hanami/pull/1382 and make for a cleaner solution. For example, instead of configuring a custom provider registrar for the slice, we could instead (for each slice container) configure a custom `Provider` subclass that "curries" the slice and makes it available as both `#slice` and `#target` to all future subclasses of itself. If this works, it would be a nicer outcome since it would mean we can achieve all of Hanami's custom provider API via just one piece of dry-system configuration instead of two.

Let me know if this doesn't make sense — I'd be happy to sketch up some code for you too.

**Comment by alassek** [comment]
@timriley Thanks for the context. That sounds like better direction than where I was at. I have mostly just been familiarizing myself with the ProviderRegistrar and how it works. 

So I'm thinking that this will entail something like a `provider_class` or `parent` configuration somewhere, probably at the point of registration? Hanami is already overloading that API so we just have to choose a different default. This would act as an alternate base class for dynamically-built Sources, unlike the current `source` option which accepts a concrete implementation.

If you have any public interfaces you'd like to see for this I'd be happy to accept some pseudocode.

**Comment by alassek** [comment]
> we could instead (for each slice container) configure a custom `Provider`

I guess you did say _configure_ a custom class. Thinking about this more, while I think you should have an option to override this at the point of registration, it would be preferable to set this once in configuration.

That would be a sharp knife, since it could impact third-party providers that don't bring their own class implementation - but this is a subsystem that Hanami users won't interact with directly so that's probably fine. Since the Hanami class would be strictly additive, this shouldn't be a risk.

**Comment by timriley** [comment]
@alassek I have a couple of different approaches in mind here, I might see if I can sketch them out in code (later this week) and run them by you for your thoughts :)

**Comment by alassek** [comment]
@timriley Now that I'm well and truly in the weeds of this thing, my assessment is that external providers should not be dynamic. The source class is reified at the point of registration into the source registry, and I bet this would likely happen before any configuration gets set.

If a third-party wants to use the Hanami provider source, they can inherit from it directly, so it's not worth it.

Instead I am going to focus on making the superclass of user-provided sources in a project dynamically switch to the hanami source. This should be a much lighter touch to the dry-system code.

**Comment by alassek** [comment]
@timriley Okay I think this dry-system change will make the desired Hanami APIs easy to add.

Open question: is it valuable to provide a `superclass:` arg in `register_provider`, or would you prefer this is strictly a matter of configuration?

**Comment by alassek** [comment]
@timriley boy, did I get more than I bargained for with this one 🙃 I'm making steady progress though.

**Comment by timriley** [comment]
@alassek Thanks for the update! But also: off! I didn't expect the Hanami side to be particularly complex, but I could certainly be overlooking some important details. If you need to share anything for some early feedback, please be my guest :)

**Comment by alassek** [comment]
@timriley Here's the current state of things if you'd like to see: https://github.com/hanami/hanami/compare/main...provider-sources

This almost worked, replacing the `ProviderRegistrar` with a custom `Provider::Source`, except for the `configure_provider` case.

I may have to do more work on the Hanami side to build the class before passing it to dry-system, or I may have to bring `ProviderRegistrar` back so that I can pass the slice as a provider option during initialization.

**Comment by timriley** [comment]
Thanks so much for sharing your work in progress, @alassek! It got the wheels in my brain spinning, and I had a go at an alternative approach.

Here you go:

- dry-system: https://github.com/dry-rb/dry-system/compare/main...provider-sources-2
- hanami: https://github.com/hanami/hanami/compare/main...provider-sources-2

So in this approach we continue to provide a `config.provider_source_class` in dry-system, but in addition, allow for custom provider registrars to pass additional args to provider sources at time of initialisation, via a `#provider_source_options` method as an extension point.

To achieve this, we have to introduce a _slight_ bit of awkwardness in that we have to pass a `build_source` proc to providers instead of the source class itself, but given that this is entirely internal to dry-system, I think it's manageable.

After this, the implementation in Hanami is all pretty straightforward!

- Create a custom `Hanami::Provider::Source` class that expects and exposes a `slice` 
- Use this for all our customer providers
- And implement `#provider_source_options` in our provider registrar to pass the slice

Tests are all green, everything works.

Let me know what you think? Given you've gone deep into this already I expect you should have some good feedback! 😄

**Comment by alassek** [comment]
@timriley Yeah, that's a much better approach! Attempting to "simplify" the Hanami side by removing the registrar actually made it more complicated. We can just close my PRs if these are ready to go.

**Comment by timriley** [comment]
@alassek Thanks for checking it out!

Now that you've seen it, here's a question for you: what if we didn't make `provider_source_class` a config option, and instead just made it another method inside `ProviderRegistrar`, e.g.

```ruby
# Extension points for subclasses
def provider_source_class = Dry::System::Provider::Source
def provider_source_options = {}
```

My thinking is that configuring `provider_source_class` on its own doesn't really achieve very much for you. If you're swapping out the source class, then you're likely also going to want to provide custom initialize args. At that point you're going to use a custom provider_registrar, so we may as well keep all the related things in one place.

In addition, removing `provider_source_class` as a config option subtly reinforces that this is an advanced feature, and probably not something users should look at unless they really want to understand the ins-and-outs of providers and provider registration (i.e. understanding `ProviderRegistrar`.

**Comment by alassek** [comment]
@timriley I agree. Simply overriding the provider source didn't get me much, as I discovered. You need to be able to pass additional state to the class, and initialization params are clearly better here than metaprogramming.

There's already an established pattern of passing kwargs from the configuring API through the registrar, so using that in combination with a custom provider makes sense.
