### ISSUE TITLE
Can't load json or json_pure

### ISSUE THREAD

**Issue by renich** [hanami/hanami#512]
Hello,

I've created a new project, in a vanilla CentOS 7.2 virtual guest and I had to add

```ruby
gem 'json'
gem 'json_pure'
```

To the Gemfile.

I do have ruby-json installed.

**Comment by joneslee85** [comment]
What version of Ruby are you using?

**Comment by jodosha** [comment]
@renich `json` is part of Ruby stdlib [since 1.9](http://ruby-doc.org/stdlib-1.9.3/libdoc/json/rdoc/) (IIRC).
Can you please check which version are you using and if you can load it from another project that uses Bundler.

> I do have ruby-json installed.

Bundler ensures isolation for each project uses it. Even if you have installed `ruby-json` on your system, in order to use it, you must include it in your `Gemfile`. This isn't Hanami, it's the reason why Bundler exist and it's used.

**Comment by renich** [comment]
I'll try to explain the case better. Here's what I did on a Vanilla CentOS:

```bash
# Setup on CentOS
## install ruby and it's deps
yum -y install ruby rubygem-bundler

## install development tools for ruby gems compilation
yum -y install @Development\ Tools 

## check which ruby tools are installed
yum list installed "ruby*"
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.pac-12.org
 * epel: reflector.westga.edu
 * extras: repos.dfw.quadranet.com
 * updates: mirror.supremebytes.com
Installed Packages
ruby.x86_64                                                                                     2.0.0.598-25.el7_1                                                                       @base
ruby-augeas.x86_64                                                                              0.5.0-1.el7                                                                              @epel
ruby-devel.x86_64                                                                               2.0.0.598-25.el7_1                                                                       @base
ruby-irb.noarch                                                                                 2.0.0.598-25.el7_1                                                                       @base
ruby-libs.x86_64                                                                                2.0.0.598-25.el7_1                                                                       @base
rubygem-bigdecimal.x86_64                                                                       1.2.0-25.el7_1                                                                           @base
rubygem-io-console.x86_64                                                                       0.4.2-25.el7_1                                                                           @base
rubygem-json.x86_64                                                                             1.7.7-25.el7_1                                                                           @base
rubygem-json_pure.noarch                                                                        1.6.3-9.el7                                                                              @epel
rubygem-psych.x86_64                                                                            2.0.0-25.el7_1                                                                           @base
rubygem-rdoc.noarch                                                                             4.0.0-25.el7_1                                                                           @base
rubygems.noarch                                                                                 2.0.14-25.el7_1                                                                          @base

# Hanami
hanami new test
cd test
bundle install
bundle exec hanami server --host=0.0.0.0
```

Now, the result of that is: 
![image](https://cloud.githubusercontent.com/assets/225115/13029540/d46eaa40-d254-11e5-9efb-4e220beb4649.png)

OK, all that said, if I just add:

```ruby
gem 'json'
gem 'json_pure'
```

To the Gemfile that `hanami new test` generated, all works.

I think that hanami should add these by it's own. Now, this doesn't happen with padrino or other frameworks. Also, I can require `'json'` and `require 'json_pure'` in `irb`

**Comment by renich** [comment]
By the way, the version is:

```bash
ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
```

**Comment by joneslee85** [comment]
FYI we no longer support Ruby 2.0 as it has reached its EOL.

**Comment by renich** [comment]
oh my... Those RHEL guys should upgrade. On the other hand, you should either reconsider or push RHEL to upgrade to 2.2. Many CentOS users in the server realm. You definitely want them to have support.

**Comment by renich** [comment]
Here's a link to the bug report. It would be cool if you could show support: https://bugzilla.redhat.com/show_bug.cgi?id=1308303

**Comment by jodosha** [comment]
@renich Thanks for the detailed explanation. Can I ask you to try another thing for us? It's just to understand if it's CentOS or us.

Install everything like you did, but instead of create a new Hanami project, just create a directory with a `Gemfile` and a basic Rack application.

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'rack'
gem 'mime-types'
```

```ruby
# config.ru
require 'bundler/setup'
require 'rack'
require 'mime-types'

class Application
  def call(env)
  end
end

run Application.new
```

Then try to start it:

```shell
bundle exec rackup
```

What happens?

**Comment by renich** [comment]
Again, `json` fails to load. Here's the test:

```bash
[renich@centos ~]$ mkdir test
[renich@centos ~]$ cd test
[renich@centos test]$ cat << EOF > Gemfile
> source 'https://rubygems.org'
> 
> gem 'rack'
> gem 'mime-types'
> EOF
[renich@centos test]$ cat << EOF > config.ru
> require 'bundler/setup'
> require 'rack'
> require 'mime-types'
> 
> class Application
>   def call(env)
>   end
> end
> 
> run Application.new
> EOF
[renich@centos test]$ bundle exec rackup
/home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:226:in `require': cannot load such file -- json (LoadError)
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:226:in `load_from_json'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:63:in `block in load_json'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:62:in `each'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:62:in `load_json'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:88:in `load'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types/loader.rb:113:in `load'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types.rb:296:in `load_default_mime_types'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types.rb:323:in `<class:Types>'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime/types.rb:63:in `<top (required)>'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime-types.rb:3:in `require'
	from /home/renich/.gem/ruby/gems/mime-types-2.99/lib/mime-types.rb:3:in `<top (required)>'
	from /home/renich/test/config.ru:3:in `require'
	from /home/renich/test/config.ru:3:in `block in <main>'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/renich/test/config.ru:in `new'
	from /home/renich/test/config.ru:in `<main>'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /home/renich/.gem/ruby/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	from /home/renich/bin/rackup:23:in `load'
	from /home/renich/bin/rackup:23:in `<main>'
```

**Comment by jodosha** [comment]
@renich So it appears to be a problem of Ruby distribution on CentOS? To move on, just add that extra gems in your `Gemfile`.

Have you considered to use `chruby` and `ruby-install` to use an official MRI dist instead of the default one?

---

Closing this.

**Comment by renich** [comment]
@jodosha I will notify them. Thank you.

Yes, I have considered it but I'd rather use my distribution's package. Packages undergo scrutiny and careful revision. Also, they're seamlessly integrated with the distribution.

In my case, Fedora and it's children (RHEL, Scientific Linux, etc) use SELinux; which is very strict about paths. Otherwise, you can't even execute some stuff. Pretty secure.

The whole distro has my back. I've got a whole community working for me if I follow their principles and lineaments. Make the distro work for you; not you for the distro.

So, those are my reasons. I thank you, very much, for the help.

**Comment by renich** [comment]
Just so you know, I've reported the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1308992

Community at work ;)

**Comment by voxik** [comment]
Hi guys,

just to explain ... in Fedora and hence in RHEL, we remove the "default gem" hack and json is installed/used as regular gem, hence there is nothing like "json" available in default load path and therefore Bundler can't find it.

In this specific case, I would blame mime-types for not specifying their dependencies. They are using json for their functionality and I can't see why they should not specify this dependency in their .gemspec. Unless it is considered soft dependency, which is not required by everybody and hence when somebody decides to use this particular functionality, (s)he should specify the dependency.

**Comment by jodosha** [comment]
@voxik but `json` is now part of Ruby stdlib. I think `mime-types` gem can safely rely on the presence of `JSON` module. Runtime dependencies declaration is designed for external gems.

```ruby
 ~:ruby-2.3.0 ➜ irb
irb(main):001:0> require 'json'
=> true
irb(main):002:0> JSON.dump({a: 1})
=> "{\"a\":1}"
irb(main):003:0> JSON.method(:dump).source_location
=> ["/Users/luca/.rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb", 385]
```

**Comment by voxik** [comment]
@jodosha I know it is part of stdlib, but not on Fedora nor RHEL. The default gems are IMHO just big hack for due to backward compatibility promises, nothing more.

**Comment by mperham** [comment]
@voxik "just a big hack" is not a good reason to break a package.  JSON is part of Ruby since 1.9, so many gems are removing their JSON dependency because they can assume it is in stdlib now.  Rails 5 will not include a json dependency: https://github.com/rails/rails/pull/23453

**Comment by voxik** [comment]
Yes, I noticed that ... and assuming something like this is mistake IMO ... Rails should move the opposite direction and every other software as well and finally the hack could be removed.

It is also just matter of time until the explicitly specified dependency will be back, due to updates in more recent version of json gem or security fixes (please see why the dependency with that specific version was there in the first place [1] and note that it was introduced in times when json was part of stdlib).

[1] https://github.com/rails/rails/commit/78cd3b0e538d7e0d3ca7869e796d98266afcd6b4

**Comment by voxik** [comment]
Not mentioning that this is not removing the dependency of course, Rails is depending on Json, you just make it hidden, nothing more. This won't help to anything. Also, you can also check the history of minitest dependency in Rails, if you like. That is similar story.

**Comment by rafaelfranca** [comment]
@voxik I'm sorry to tell this to you but `json` is not going to be explicit dependency of Rails again. We trust that the Ruby distribution will distribute its defaults gems and we will keep trusting that.

If there are security updates needed in json gem we will do exactly what we do with rack, sprockets and any other gem we depend, nothing. If there is a security release in these gems we recommend users to upgrade but we don't bump or release a new Rails version because of that.

`json` is a dependency of Ruby and we will keep considering that way.

**Comment by voxik** [comment]
@rafaelfranca you probably do not realize, that any gem in the Rails app dependency chain can force to load old version of json now, which might be either incompatible or vulnerable ... btw if you want to be really consistent in what you are saying, I'd suggest to remove dependencies on rake and minitest as well, since they are part of stdlib ... and btw sdoc still refers json explicitly.

**Comment by sardaukar** [comment]
@voxik apologies if I appear brutish, but why is Fedora/RHEL so keen on imposing their rules about what should happen, and not following Ruby packaging standards that work for every other platform?

**Comment by renich** [comment]
Guys, keep it in scope. The idea here is that hanami works fine on all major distributions. 

Adding a json dependency seems minor. The major issue; which is discussing the philosophical context of json being in stdlib or not should be taken to ruby's issue tracker and discussed there.

Let's not turn this issue into a flame.

**Comment by jodosha** [comment]
@renich Thanks for your words in my absence.

**Comment by renich** [comment]
@jodosha no worries, dude.

**Comment by martinpovolny** [comment]
@voxik : with all respect, Fedora and RHEL forces you to explicitly declare something that is implicit in the upstream Ruby. So on Fedora and RHEL you have to write code in a different way that in upstream Ruby. Many developers don't care about Fedora and RHEL because they run on Mac or Ubuntu or whatever else and do not care about Fedora or RHEL. They write software that runs well on upstream Ruby but fails miserably on Fedora and RHEL due to changes made by Fedora and RHEL. I see the resulting situation as a bug and I am not alone with that view. Actually from the hundred or so Ruby developers I personally know I can name a few who understand the motivation behind this and you are probably the only Ruby developer I know personally who actually advocates it.
