### ISSUE TITLE
Follow ruby code style convensions

### ISSUE THREAD

**Issue by aderyabin** [hanami/hanami#514]
As an idea, I suggest to follow Ruby code style fully described by Bozhidar ([link](https://github.com/bbatsov/ruby-style-guide)) and integrate Rubocop. 

I saw the discussion about Rubocop [here](https://github.com/hanami/hanami/pull/171) but let's back to the question again. Yes, I know that default Rubocop config is angry, but we can modify it. 

From my side I'm ready to start working on Rubocop integration, but I'm interested in thoughts by @jodosha, @jeremyf and @joneslee85 before starting.

**Comment by jodosha** [comment]
@aderyabin Hello and thanks for this discussion. Are you talking about the internals of the framework or about the generated code (aka Hanami projects)?

**Comment by aderyabin** [comment]
@jodosha Both.
as the example, look at this lines https://github.com/hanami/hanami/blame/master/lib/hanami/commands/generate/app.rb#L64-L73.
Ten lines of code and two different styles `#{app_name}` and `#{ app_name }`.

Or another example. Hanami codebase has both `raise` and `fail`. 

Yes, there are a lot more important tasks, but Hanami is enjoying the beauty, and code should be beautiful too, I believe.

**Comment by jdickey** [comment]
I've been using RuboCop on all my projects for years but, in the last year or so, I've had the sense they're going deep into the fringe. They've flip-flopped on a couple of style conventions as time has gone on.

I've locked my current projects to RuboCop 0.35.1, with a simple [configuration file](https://gist.github.com/jdickey/970d70a9b58fe5519d50) to override exactly two defaults:

<script src="https://gist.github.com/jdickey/970d70a9b58fe5519d50.js"></script>

Lately, I've been relying far more on Tim Roessner's [Reek](https://github.com/troessner/reek) for most of my style enforcement; you may want to take a look at it, too.,

**Comment by jodosha** [comment]
@aderyabin Absolutely not for the internals of the framework. Sorry, but we can't afford this change.

For the Hanami projects it depends on how much work it is for us and how much demand it's out there. I never used RuboCop because I feel it too strict. I'm with @jdickey on this.

**Comment by joneslee85** [comment]
@aderyabin i am too a big fan of strict code linting but I do find it is annoying at times, especially for contributors. But I am all for small clean-up commits (submitted along with big PRs) to make the code more consistent.

**Comment by jbodah** [comment]
For what it's worth, we've taken the stance in our internal projects of disabling all of the cops and only re-enabling some. Moreover, we've had a ton of success using `rubocop --auto-correct` for the vast majority of the corrections.

Here's what our internal cop config looks like: https://gist.github.com/jbodah/13e07de39c3b7bdc2fcd

The real juju for us is [AllCops/DisabledByDefault](https://github.com/bbatsov/rubocop/pull/1991):

```yml
AllCops:
  DisabledByDefault: true
```

**Comment by jodosha** [comment]
@jbodah Is your usage of Rubocop similar to `go fmt`? Do editors and IDEs support Rubocop and automatically apply the rules? I'm asking cause I never used it for long time.

**Comment by jbodah** [comment]
> @jbodah Is your usage of Rubocop similar to go fmt? Do editors and IDEs support Rubocop and automatically apply the rules?

I'd say it's similar. I personally run rubocop with a pre-push hook and run `--auto-correct` manually. I don't know if plugins already exist for most editors or not, but I think it would be trivial to make it like `go fmt` (e.g. with vim just add a BufPreWrite autocommand or something). Rubocop has pretty good caching, so it's pretty fast to do an entire project and you can also limit it to whatever you're working on by passing it that file.

We've also added rubocop to our rake default task

**Comment by jodosha** [comment]
> We've also added rubocop to our rake default task

At a previous company, we had it enabled as CI task to pass. It's painful to discover at the build time that it won't pass because of style violations. It's better to have a "fail fast" strategy and have it enabled in a editor (if possible).

---

Now, my question is. Did someone scan a Hanami project with Rubocop? If so, what's the outcome?

**Comment by jbodah** [comment]
> Now, my question is. Did someone scan a Hanami project with Rubocop? If so, what's the outcome?

Just did a quick run of this on `hanami/hanami`. There are around 2300 offenses with the out of the box config, half of which are auto correctable (but we'd probably want to double check).

`rubcop --auto-correct`

That leaves 1000 or so. Filtering out `LineLength` and ignoring the `test` directory leaves around 100 offenses, many of which are similar (lack of top-level docs, long methods)

`rubocop --except LineLength lib`

**Comment by cllns** [comment]
Thanks for opening this @aderyabin :+1:. I'm in favor of adding a custom `.rubocop.yml`, to ensure code within the `hanami` project is consistent. I don't care about following 'the' Ruby Style guide (mostly because I personally disagree with some of their recommendations :stuck_out_tongue: ). Instead, `.rubocop.yml` should enforce the style `hanami` already uses.

I've used [`overcommit`](https://github.com/brigade/overcommit) to add a pre-commit hook and I've been happy with that. Only downside is that contributors have to run `overcommit -i` to install the hooks if they want them to run. (If they don't run it, there are no errors, it just doesn't run the pre-commit hooks). In those cases, CI could take care of any violations, in the PR). I've also added `rubocop` to the default rake task and I recommend that as well.

@jodosha: Many [editors have integrations](https://github.com/bbatsov/rubocop#editor-integration).

I think it's worth the effort; I'm happy to help. I imagine the work will mostly be tweaking individual 'cops', then coming up with a list of potentially controversial ones to either [bikeshed](http://bikeshed.com/)  or ignore (with `AllCops/DisabledByDefault`).

For an example of tweaking one 'cop' (rule), the `ruby-style-guide` says lines shouldn't be longer than 80 characters. In `hanami/hanami` there are:

-  819 instances of lines longer than 80 characters.
- 122 instances of lines longer than 120 characters.
- 36 instances of lines longer than 150 characters.
- 8 instances of lines longer than 180 characters.
- 3 instances of lines longer than 200 characters. 

I think 120 is a reasonable limit, but perhaps 150 makes more sense in this case. 
Rubocop allows you to set rules for new code, but ignore existing violations, with [a `rubocop_todo.yml` file](https://github.com/bbatsov/rubocop#automatically-generated-configuration). (you can also do that [in code](https://github.com/bbatsov/rubocop#disabling-cops-within-source-code) but I'm against littering the source code in order to make it look better :smile: )

**Comment by jodosha** [comment]
Folks, thanks for checking `hanami/hanami`, but as stated above, applying Rubocop rules to the project is out of question now. We have more important things to address right now.

> Did someone scan a Hanami project with Rubocop?

If it won't take too much effort, we can make Hanami projects compliant with Rubocop. What I mean, is the output of `hanami new bookshelf && cd bookshelf && bundle && rubocop`. In an ideal world, I would love to have interesting stats of projects out there.

I used @jbodah 's configuration for a project of mine, the most common offence is the space inside the interpolation string. Eg `"#{ __dir__ }/test"`.

**Comment by cllns** [comment]
I just tried fixing the templates to follow the `ruby-style-guide`. I don't think it's worth doing.

For one, we can't even guarantee that it'll pass the default rubocop style guide 100% of the time, because of the 80 characters per line limit.

For example, take a look at the [`app_name.rb` template](https://github.com/hanami/hanami/blob/master/lib/hanami/generators/application/app/lib/app_name.rb.tt#L13-L20).
We could refactor those lines to less than 80 characters. Having method calls in comments go to two lines isn't a nice looking, but the big issue is that if someone generated an app with a long name, it'd make that line go over 80 characters.

We could try to accommodate the other rules?

Though this one is pretty offensive to me :innocent::
```
-      load_paths << [
-        'controllers',
-        'views'
-      ]
+      load_paths << %w(
+        controllers
+        views)
```
That being said, I think `rubocop` can be used to improve the templates, when it makes sense. For example:
```
-      security.x_frame_options "DENY"
+      security.x_frame_options 'DENY'
```

**Comment by jodosha** [comment]
I started to use Rubocop because of day job. It's activated on my Vim setup, so new code is respecting Ruby community standards.

This is a principle rather than a task. I'm not willing to change the entire codebase in a single day.
