### ISSUE TITLE
Generated relative path inaccurate for nested actions

### ISSUE THREAD

**Issue by berfarah** [hanami/hanami#542]
If I do

```shell
hanami g action app foo/bar#baz
```

All the files generate in the right places, but the `require_relative` is inaccurate. Because of the additional directory nesting, it needs one more `../`

What I get:
```ruby
# apps/foo/controllers/bar/baz.rb
module Foo::Controllers::Bar::Baz
end

# spec/foo/controllers/bar/baz_spec.rb
require_relative '../../../../apps/foo/controllers/bar/baz'

# should be
require_relative '../../../../../apps/foo/controllers/bar/baz'
```

The code is [here](https://github.com/hanami/hanami/blob/ec6411c77b38b87e1e162e1c5bb73ade9da4642f/lib/hanami/commands/generate/action.rb#L236). I believe the @controller_pathname could be scanned for slashes and then additional `..` could be added based on that.

Here's a quick and dirty way of fixing it:
```ruby
def relative_action_path
  nestings = @controller_pathname.count('/') * ['..']
  path = Pathname.new('.').join('..', '..', '..', *nestings)
  path = path.join('..') if environment.container?
  path.join(application_path, 'controllers', @controller_pathname, @action_name.downcase)
end
```

Thoughts?

**Comment by cllns** [comment]
:+1:  Good find and fix, IMO.

1. The code for `relative_view_path` is nearly identical. Can you check to make sure there's no issue with `views` too?

2. A tiny tiny style thing: how do you feel about adding `'..'` when `environment.container?` to the `nestings`, since that's a variable now? That way we only call `join` once. E.g.
  ```
    nestings = @controller_pathname.count('/') * ['..']
    nestings << '..'  if environment.container?
    path = Pathname.new('.').join('..', '..', '..', *nestings)
  ```
  But if you think it's better as is, no problem. My solution is same number of lines so ¯\_(ツ)_/¯
 
3. Can you add tests?

**Comment by berfarah** [comment]
Thanks @cllns! Sounds good on all counts. I'll work on this and submit a PR once I'm off work.
