### ISSUE TITLE
Explicit documentation that "Flash" word is a reserved key for Action layer

### ISSUE THREAD

**Issue by rafaels88** [hanami/hanami#595]
This is just a request to put this information in documentation.

I was trying to create a simple system for flash message using session + shared code, and no errors occured, but exposed `:flash` attribute always had `{}` as value.

#### Steps to reproduce

```ruby
# apps/web/controllers/flash.rb
module Web
  module Flash
    after :flash!
    expose :flash

   private

   def flash!
     @flash = {}

     if session[:flash_message]
        @flash[:success] = session[:flash_message]
        session[:flash_message] = nil
    end
  end
end
```

```ruby
# index.html.erb
<%= flash[:success] %>
```

#### Actual behavior
Rendering result will always be `{}`.

#### Expected behavior
Should be == `session[:flash_message]`.

I figured that `Flash` is a kind of internal module for Hanami Controller, so this issue is just a request for this to be documented.

**Comment by cllns** [comment]
Thanks! Good find. [Indeed `flash` is used in `Hanami::Action`](https://github.com/hanami/controller/blob/master/lib/hanami/action/flash.rb).

Personally, I'd rather see an error telling the developer that `flash` is reserved (and links to docs about flash) rather than just document it.

What do others think about that? If that's desired, this should be filed in in `hanami/controller`.

**Comment by b264** [comment]
:+1: for `raise` telling developer `flash` is reserved

**Comment by rafaels88** [comment]
:+1: for `raise`.

**Comment by jodosha** [comment]
Yes, this should go in `hanami-controller`.

**Comment by cllns** [comment]
We can close this, in favor of this Issue in `hanami-controller`:  https://github.com/hanami/controller/issues/158

**Comment by jodosha** [comment]
@cllns Thank you 👍
