### ISSUE TITLE
Tests failing due to some changes in dry-validation

### ISSUE THREAD

**Issue by tejasbubane** [hanami/hanami#598]
Hanami tests are failing due to some changes in `dry-validation` gem. Did a git bisect and found [this commit](https://github.com/dry-rb/dry-validation/commit/adaad49399f4ee807693e87c0aff85f8a2fa71f0) to be the reason.

Stack-trace of test failure can be seen here: https://travis-ci.org/hanami/hanami/jobs/138377424

Any specific reason for using direct github for external gems (apart from hanami gems)?

**Comment by jodosha** [comment]
@tejasbubane Hey, thanks for reporting this problem. I fixed it.

> Any specific reason for using direct github for external gems (apart from hanami gems)?

We recent rewrote `hanami-validations`, by using `dry-validation` as internal engine. Because `dry-v` changes a lot between 0.7 and the upcoming 0.8, we decided to base our rework of `hanami-v` on their master version. In this way, once `dry-v` 0.8 will be out, we don't need to port anything, but we can release `hanami-v` at any time.

However, living on the edge, can cause issues like the one you reported.
