### ISSUE TITLE
generating model results in uninitialized constant [EntityNameHere] (NameError)

### ISSUE THREAD

**Issue by chellberg** [hanami/hanami#611]
see it [here](https://github.com/chellberg/hanami-entity-generator-test)
(boring) [Gemfile.lock](https://gist.github.com/chellberg/2d43925bbbdedd9919cae87c6407bf91)

I ran ```hanami new entity-generator-test --database=postgres``` to generate the project, then `bundle exec hanami generate model game` to generate my `Game` entity and repository. 

To repro, clone and run `rake`. The generated entity spec fails with `uninitialized constant Game (NameError)` on `describe Game`, and I get the same error trying to instantiate a `Game` in `hanami console`

Suggestions? Apologies if I missed something obvious!

**Comment by jodosha** [comment]
@chellberg I'm sorry about this problem.

We use `config/environment` to require the main file in your model domain: `lib/entity_generator_test.rb`. It's responsible to preload all the entities and repositories with the following line:

```ruby
# lib/entity_generator_test:3
Dir["#{ __dir__ }/entity_generator_test/**/*.rb"].each { |file| require_relative file }
```

It looks for _"snake case"_ directories (which is right), but the generated structure uses dashed names:

```shell
➜ tree lib
lib
├── config
│   └── mapping.rb
├── entity-generator-test # <= THIS IS WRONG
│   ├── entities
│   │   └── game.rb
│   └── repositories
│       └── game_repository.rb
├── entity_generator_test
│   ├── entities
│   ├── mailers
│   │   └── templates
│   └── repositories
└── entity_generator_test.rb
```

---

It's now fixed in master. To try it, please have a look at: https://github.com/hanami/hanami#how-to-use-hanami-head

---

Ref #491

**Comment by chellberg** [comment]
Nice! Thanks so much @jodosha
