### ISSUE TITLE
why is not sequel the default ORM or provide a flag to generate the project with this?

### ISSUE THREAD

**Issue by mrkaspa** [hanami/hanami#635]

**Comment by cllns** [comment]
@jodosha is working to change the back-end of `hanami-model` to use Ruby Object Mapper (rom) instead of Sequel. 

You're free to use Sequel. `hanami-model` is *not* a dependency of the full `hanami` framework. Instead, we include `hanami-model` in the generated Gemfile. This makes it easy for you to swap it out for something else. Just remove `hanami-model` and add `sequel`.

Also, we prefer Issues have a Description, so we can fully understand your reasoning and question.

**Comment by mrkaspa** [comment]
@cllns great thx

**Comment by jodosha** [comment]
Because this is a recurring question, I added an article in our Guides with the instructions: https://github.com/hanami/hanami.github.io/commit/bf8d879cd613a91e7536fa5bf42158573204c9b7
