### ISSUE TITLE
Move mailers to apps

### ISSUE THREAD

**Issue by sandelius** [hanami/hanami#648]
In my opinion mailers are not part of the business logic and should be moved into each app. SMTP configurations might go in ./config/mailer.rb or something tho.

I've looked at the source and I think we need to duplicate the mailer the same way we do with the view layer.

What do you guys think about this?

**Comment by mereghost** [comment]
Hmmm... not sure if that is so black & white. I can agree that some mailers are unrelated to the business logic and may be part of the apps, but surely not all of them.

If you want to send an email to a new user for confirmation, you might want to do that for every app that you may have. The templates might (or not) differ a bit, but the business value is there.

**Comment by jodosha** [comment]
@sandelius Is right and I agree. This was already in my mind for long time.

As of `hanami` 0.8.0, mailers are inside project's `lib/`. This choice was demanded by one golden rule of Hanami: let the applications (`apps/`) to depend on core (`lib/`), but **not** viceversa.

Because the core usually includes _interactors_ and they may want to deliver emails, we were forced to put emails in the core too (`lib/`).

This is wrong because:

  * Mailers are deliverability mechanisms (like web apps), so they should belong to the deliverability part of Hanami projects (`apps/`).
  * Mailers may want to access to assets, which is impossible from the core (`lib/`), but only allowed from applications (`apps/`).

So mailers should be moved under `apps/`.

**Comment by TiteiKo** [comment]
Just a thought here... How about a `mailers/` root directory?

Mailers are deliverability mechanisms, but are not web apps, so they should not be in the apps directory. 

It would allow mailers to have their own assets access, and be accessible from interactors or across different apps (like an admin app re-sending an user confirmation email for example)

**Comment by cllns** [comment]
I like @TiteiKo's suggestion. Especially the reasoning: `Mailers are deliverability mechanisms, but are not web apps, so they should not be in the apps directory.`

**Comment by jodosha** [comment]
@TiteiKo Interesting abstraction. But I'm afraid, this would introduce a bunch of new problems. Circular dependencies between components, where an action from `apps/web` will depend on a mailer in `mailers/`, which may depend on the routes/assets/helpers from `apps/web`.

How could we solve this?

**Comment by TiteiKo** [comment]
**Helpers:** If a helper is required in several apps or in apps and mailers, it should be placed in `lib/`. 

**Assets:** Assets for mailers are quite different from assets for apps: no js, css is in the `head` section and images in a size and format fit for emails. Nowaday, people read their emails mostly on small screens, with a not-so-great bandwidth, so jpg is the best choice, where png is better for computer-targeted apps.

**Routes:** This is the only valid dependency IMHO. We could use `TheApp.routes.the_path`, so a mailer may be able to generate links to different apps and be app-agnostic. No problem here while fully launching the project, and it can easily be mocked while testing a mailer.

**Comment by jodosha** [comment]
All the helpers, assets, and routes depend on the associated application's configuration.

That means we can't pull out helpers in `lib/` and we can't reference `TheApp.routes` from `lib/` because this would create circular dependency between the code defined in `lib/` and the code defined in `apps/`.

---

> Assets for mailers are quite different from assets for apps: no js, css is in the head section and images in a size and format fit for emails. Nowaday, people read their emails mostly on small screens, with a not-so-great bandwidth, so jpg is the best choice, where png is better for computer-targeted apps.

I don't understand how mobile email requirements affect us. From our perspective, embedding an asset in an email it's the same if they decide to go for a 10Mb jpg or a 2k png 😉

**Comment by BenBach** [comment]
I totally agree that this should be outside of lib since it's own delivery mechanism.

How are you handling this right now? The assets is not really an issue for me since I serve them from a bucket for static files.

But I am struggling how to use **routes**. Right now I didn't find a good way to achieve this. Did someone already did a good workaround? (e.g. "Confirm your email address")

**Comment by TiteiKo** [comment]
@jodosha I've been thinking a lot about this since @BenBach comment...

Structurally speaking, I'd do something like this:

```
│
├── apps
└── mailers
    ├──  assets
    │   ├── stylesheets
    │   └── images
    ├──  config
    │   └── route_builder.rb
    ├──  emails
    ├──  templates
    └──  views
```

Because emails usually are complex. More than just static text, they can have routes, they often need to retrieve stuff from the database, etc etc.

It is really close to a website classic page delivery:
* the email (or call it what you want) class determines the delivery method (html/txt), the expeditor and receiver, attaches stuff... It also retrieves data (using classes in `/lib`) and sends it to...
* the view, that puts it into form (formats dates and stuff) and renders...
* the template, which uses...
* assets, that usually are specific to the mailing part of the system (the point I tried to make last year)

**How about the routes?**

Well, we don't **need** routes _per say_... We just need to be able to **construct** routes. To any application. And that's **really easy**

```ruby
module Mailers
  class RouteBuilder
    def user_email_adress_confirmation_route(token:)
      "/my_route/#{token}"
    end
  end
end

def test_user_email_address_confirmation_route
  route = Mailers::RouteBuilder.new.user_email_address_confirmation_route(token: 'azerty')
  assert_equal 'web_controllers/users#confirm_email', Web.routes.recognize(route).action
end
```

This way, you have your mailers that are app-independant and cross-app, which means that an email can contain links to any app. It also mean that any app can send any mail (think "button to send a confirmation email again from the admin panel"), and that any mail can be sent in the background, where your apps don't need to be loaded.

**Comment by BenBach** [comment]
@TiteiKo Thanks so much for provided such a nice and clean solution proposal.

I will try that out.

The point which got me concerned at first was that I can't use route helper methods from the specific apps. So if a route changes in an app the mailer won't know it.
But actually this makes total sense: Routes are an interface of an application as well. It's a contract, which you should rarely / never change.

**Comment by jodosha** [comment]
I'm closing this for now, as not immediately actionable.
