### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by arjunmenon** [hanami/hanami#658]
This is an issue.

In the overview itself, it is mentioned change would be a challenge. Learning Hanami would be hard. That is because, Rails has become THE way to develop web app and so, the style, architecture it follows, guidelines, philosophies, principles, conventions has been accepted and become muscle memory.

The issue here is, the Hanami docs don't mention how much and in what way it differs in it's style of doing things from Rails.

If that was there, I think the new way you guys are suggesting would become easier to follow. Easier to understand. And much easier to try, develop and deploy.

Please consider making life a bit easier.

_PS - What's with the thin, grey font. Docs are meant to be readable._

**Comment by cllns** [comment]
Thanks for this issue! We all agree docs are super important, and we appreciate the honest feedback. Really.

I like the idea of developing some sort of "mission statement" or even just listing some "guiding principles" for Hanami, like _simple_ vs. _easy_. Single-responsibility principle (or even [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) as whole), [Domain-driven design](https://en.wikipedia.org/wiki/Domain-driven_design), etc. It could be a revamp of [this page](http://hanamirb.org/guides/). This would be useful documentation for newcomers, but also would help with community direction and even marketing.

Rather than spending a lot of time reading about Hanami, we want people to try it out so they can see for themselves. So people can be like "Oh yea, an Action makes sense as a class, whereas a single class for a Controller conflates a lot of mixed concepts and doesn't adhere to the Single-responsibility principle" and so-on, for the different components. Rather than positioning Hanami as "better than Rails", I think we'd prefer to just say and show that Hanami is great, without trying to pick a fight. A direct comparison of how Rails does things to how Hanami does things better belongs in [blog posts](http://teotti.com/rails-vs-hanami/) rather than official documentation.

What are your thoughts on that?

(These are just my personal interpretations and opinions. I'm not speaking for @hanami/core-team or @jodosha.)

Thanks too for the comment about the light font. I think the site design and font lightness fits well with the "simplicity" theme, but it's not the most readable. [We welcome PR's to the documentation site](https://github.com/hanami/hanami.github.io). :)

**Comment by jodosha** [comment]
The main page of the Guides has to be improved, because since when we wrote it, we added more and more value to the framework. Some of these new Hanami features are worth to be mentioned over there.

**Comment by jodosha** [comment]
@arjunmenon Thank you for the suggestions. I've opened tickets over our website's repository.
