### ISSUE TITLE
Expand `rake spec` commands

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#689]
Right now, `bundle exec rake` is equivalent to `bundle exec rake spec:unit`.

There's no way to run only integration or isolation specs, other than `bundle exec rspec spec/integration` (etc.)

I propose we add:
- `rake spec:integration`
- `rake spec:isolation`
- `rake spec:all` (aliased to just `rake spec`, to make it easy)

And keep `rake` as `rake spec:unit` so people can run speedy tests when contributing.

Might be able to leverage these commands to make the [`script/ci`](https://github.com/hanami/hanami/blob/master/script/ci) command simpler :)

**Comment by AlfonsoUceda** [comment]
thanks @cllns !! I agree with the proposal.

**Comment by jodosha** [comment]
@cllns Thanks for your suggestion, but this isn't possible. 😉 

---

Isolation and integration tests require a high level of isolation. There are cases where we simulate the absence of `hanami-model` and cases where we force to boot twice a project to prove it's working properly.

Unfortunately with Ruby the safest way to isolate global configuration is to use separated processes. That's why `script/ci` uses bash to start separated RSpec/Ruby processes for each file: to guarantee a high level of isolation between the tests.

---

Using Rake will force us to use the same Ruby process for **all** the tests in a given group. This limits reduces the level of isolation to a level that isn't useful for us.

We can spawn a child process for each file. But trick this won't help to test projects where we have different set of bundled gems. There are cases where we bundle haml (or slim), webrick (or puma) etc..

**Comment by cllns** [comment]
@jodosha Thanks for the info and detailed response. What if the rake task called a bash script like `script/ci`? Wouldn't that still create a new process for each?
