### ISSUE TITLE
Community adjectives

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#691]
Currently, we say: "We strive for a Community made of **inclusive, helpful and smart people.**"

Should we drop "smart" here? Everyone using Hanami is clearly already smart 😉 

But seriously, I feel like specifically wanting "smart" people implicitly means we don't want "dumb" people. I would hate it if someone refrained from asking a question for fear of being seen as not "smart".

We could replace it with something else. How about "inquisitive" or "curious"?

 Assigning to @hanami/community

**Comment by oana-sipos** [comment]
@cllns I must admit that ”smart” caught my eye the first time I have read it. I would vote for ”curious” for now. The sole alternative that comes to my mind is ”open minded”.

**Comment by marionschleifer** [comment]
@cllns @oana-sipos
First of all, sorry for my late reply, I am still on holidays. I would also drop "smart", but I am not sure if I would go with "curious". I like "open-minded", because I think in this context, it has more meaning. I think when you work in a community, being open-minded is more important than being curious. However, "curious" is also not bad...

**Comment by beauby** [comment]
How about not replacing it at all, and talking about the community itself, rather than its members?
> We strive for an inclusive and helpful community.

This would also emphasize the community over the individuals, and thus not put a burden on people to intrinsically being in a specific way, but rather to behave according to the community's standards.

**Comment by oana-sipos** [comment]
Sounds like a better direction @beauby. Like it!

**Comment by marionschleifer** [comment]
@beauby great idea!

**Comment by cllns** [comment]
I agree @beauby. great reasoning!

It needs to fixed in this repo and in the website repo: https://github.com/search?q=org%3Ahanami+%22smart+people%22&type=Code

**Comment by oana-sipos** [comment]
Thanks @cllns for the pointers. I can take care of adjusting it and submit a PR, just to be safe :)

**Comment by jodosha** [comment]
@hanami/community Please fix this according to the decision taken in this discussion.

**Comment by marionschleifer** [comment]
@jodosha @oana-sipos I submitted a PR :)

**Comment by cllns** [comment]
Thanks @marionschleifer, I merged it. Can you take care of this one too (on the Community page): https://github.com/hanami/hanami.github.io/blob/2c2d6e0bb804d0cdefa60dece07475206557ca8e/source/community.html.erb ?

**Comment by jodosha** [comment]
Closed by #699

**Comment by marionschleifer** [comment]
@cllns Of course. Will do it tonight or tomorrow :)

**Comment by marionschleifer** [comment]
@cllns I made the PR :)
