### ISSUE TITLE
`hanami db prepare test`

### ISSUE THREAD

**Issue by moofkit** [hanami/hanami#728]
To setup test database need to use `HANAMI_ENV=test bundle exec hanami db prepare`.
It is ok, but may be it will be usefull to have shortcut like `bundle exec hanami db prepare test` to prepare/migrate specific enviroment database? It seems to me as very natural behavior.
WDYT?

**Comment by cllns** [comment]
Yes, I've noticed this too, and I agree it's a poor user experience.

A couple other options for solving the same problem:
- make `bundle exec hanami db prepare` prepare *both* `development` and `test` databases by default.
- run any migrations that haven't been run yet in `spec_helper.rb`, so developers wouldn't have to worry about migrating the test DB at all. though, this might make running tests slower

**Comment by moofkit** [comment]
@cllns 
As I understand `db prepare` is safe operation and if database already created it just run migrations.
So I find very usefull this options too.

Can I try to implement this feature if you don't mind?

**Comment by davydovanton** [comment]
I don't like `db prepare test test` command. I worried that this command would complicate our CLI code.

But, if we want to use `prepare` command for dev and test envs we can introduce `--all` key. WDYT?

**Comment by mereghost** [comment]
@moofkit [Prepare](https://github.com/hanami/model/blob/master/lib/hanami/model/migrator.rb#L283) isn't "safe". It drops the database, re-creates it and then run migrations.

On the convenience side of things I can see why using the environment variable can be a pain. OTOH it keeps the CLI consistent. If we add a special case for `db`, we would need one for console, db console just to keep up with the POLS.

**Comment by AlfonsoUceda** [comment]
I prefer use `HANAMI_ENV=test bundle exec hanami db prepare` than `bundle exec hanami db prepare test`, but it just my opinion.

**Comment by jodosha** [comment]
@moofkit 
> As I understand db prepare is safe operation and if database already created it just run migrations.
> So I find very usefull this options too.

Nope. 😄 

`db prepare` == `db drop` + `db create` + `db migrate`.

---

I vote against this change, because it would be inconsistent with the other commands in the CLI.

---

One improvement can be `--environment=test`, aliased as `-e test` to add across all the commands. But for now we can't do this change because that option was taken for another purpose:

```shell
➜ bundle exec hanami server --help | grep env
      [--environment=ENVIRONMENT]                # Path to environment configuration (config/environment.rb)
```

That was a poor choice, my apologize, but for now we're stuck with it.

---

@davydovanton 

> But, if we want to use prepare command for dev and test envs we can introduce --all key. WDYT?

To me `--all` isn't communicative, as there isn't a reference to the concept of environment. Also, it isn't really "all" but development and test.
