### ISSUE TITLE
Publish release notes for services like sibbell.com?

### ISSUE THREAD

**Issue by zavan** [hanami/hanami#739]
[Sibbel](https://sibbell.com/) is a service that notifies devs about package updates:

![image](https://cloud.githubusercontent.com/assets/1722965/23525111/11c5bb78-ff6c-11e6-92e0-205fe89653d4.png)

It shows release notes in the email and website:

![image](https://cloud.githubusercontent.com/assets/1722965/23525205/6541a172-ff6c-11e6-8961-0e3fb9a41d18.png)

But not when they're not filled :(

![image](https://cloud.githubusercontent.com/assets/1722965/23525223/79e3faee-ff6c-11e6-9fbf-b9334d94f244.png)

So it would be nice if you could include release notes with the tags.

(I'm not affiliated to sibbel in any way)

**Comment by cllns** [comment]
I think a more pressing reason would be including the notes on the Releases page, rather than this specific tool. For example:
![image](https://cloud.githubusercontent.com/assets/632942/23804646/084c2b9c-0578-11e7-992c-5ef72a5cfff9.png)

vs Hanami's release page: 
![image](https://cloud.githubusercontent.com/assets/632942/23805020/7427e580-0579-11e7-8f22-7354d7c21333.png)


It looks like the way to do this is through GitHub's UI: https://github.com/blog/1547-release-your-software and the notes aren't stored within Git itself, but on GitHub.

`hanami*` Releases are done with `bundle exec rake release`. It [looks like GitHub release notes are not supported](https://github.com/bundler/bundler/issues/4904). We'd have to implement this ourselves, plus complicate the release process, by dealing with GitHub API tokens.

Some relevant discussion: https://github.com/olivierlacan/keep-a-changelog/issues/1

Seems like a lot of work for a minor nice-to-have feature :/

What do you think @zavan (and others)?

**Comment by jodosha** [comment]
@zavan Hey, thanks for your suggestion. How does Sibbel work? By manual entry from us?

**Comment by zavan** [comment]
@jodosha It fetches your GitHub faved repos and sends you an email when there's a new release/tag, in the email it sends the changes if they're on the GitHub release. Refer to @cllns for how to publish the changes.

@cllns I agree that integrating this in the release process is too much work for a "nice to have", I'd just CTRL+C/CTRL+V the markdown from the CHANGELOG into the GitHub release, since they're not THAT frequent after all.

**Comment by jodosha** [comment]
@zavan Gotcha. Thank you.

> I agree that integrating this in the release process is too much work for a "nice to have", I'd just CTRL+C/CTRL+V the markdown from the CHANGELOG

This can work.

**Comment by AlfonsoUceda** [comment]
We can try that for the next version.

**Comment by jodosha** [comment]
Okay, let's give it a shot. @AlfonsoUceda please take care of this.

Closing this issue as "fixed".

**Comment by cllns** [comment]
@AlfonsoUceda This is the page you need to add release notes: https://github.com/hanami/hanami/tags (have to switch to the 'Tags' tab, 'Releases' doesn't show any options for editing the release notes)

**Comment by AlfonsoUceda** [comment]
@cllns thanks for the comment ;)
