### ISSUE TITLE
Generate readme.md file for new project

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami#759]
We all love readme files. We use it in our public and private projects. And that's why I think we should generate simple readme with project name.

WDYT?
/cc @hanami/core

**Comment by cllns** [comment]
I don't think this is necessary, but I'm OK with it as long as it's very short and not-too specific. I personally prefer having no README to having an outdated boilerplate one :)

I generally just create a README once I need it.

**Comment by AlfonsoUceda** [comment]
IMO this is not need, I'd leave the responsibility to the user

**Comment by jodosha** [comment]
@davydovanton Can you please specify what do you think goes inside the `README`?

**Comment by davydovanton** [comment]
@jodosha I think it will be good if we will generate base `README` file with this parts:
- Project name and description
- How to start project (for new developers)
- Or maybe copyright

In general, I see that this readme file will look like bundler generated readme file for each gem

**Comment by jodosha** [comment]
Good for me 👍

**Comment by jodosha** [comment]
What the rest of @hanami/core thinks? 😸

**Comment by cllns** [comment]
No README is better than having a generic, generated README, IMO :)

**Comment by davydovanton** [comment]
merged to `develop` branch

**Comment by cllns** [comment]
Can we reconsider this, please?

Generating a file with 3 `TODO`'s seems pointless. 

I don't think we need to generate this file at all, but if we do, can have it mostly blank, rather than having a bunch of boilerplate that needs to be deleted? 


Also, I don't think we should be saying the project is licensed on MIT. Most Hanami projects will be closed-source, and I don't think they'll want to license it with MIT. (Is a line in the README sufficient? I don't know, but I see other projects with a `LICENSE` file) If we want to add license support, it should be a `.hanamirc` option IMO, and that seems like overkill for a README.

**Comment by davydovanton** [comment]
@cllns nice point 👍

**Comment by TiteiKo** [comment]
@cllns :+1: on the license point. 

IMHO: if we generate a generic readme with more content than a title, it should contain useful and hanami-specific informations:
* how to run the tests
* how to run the console
* how to setup the dev environment (db setup)

Those are informations that are good to have in the readme of any project.

**Comment by AlfonsoUceda** [comment]
Agree @cllns and @TiteiKo 👍
