### ISSUE TITLE
Got many warning when start hanami server

### ISSUE THREAD

**Issue by opan** [hanami/hanami#769]
Hi, firstly thank you for this great framework.
Okay, to the point. I have got a lot of warnings when I started `hanami server`. Here is the log:

```
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/version.rb:4: warning: already initialized constant JSON::VERSION
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/version.rb:3: warning: previous definition of VERSION was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/common.rb:100: warning: already initialized constant JSON::NaN
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/common.rb:99: warning: previous definition of NaN was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/common.rb:102: warning: already initialized constant JSON::Infinity
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/common.rb:101: warning: previous definition of Infinity was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/common.rb:103: warning: previous definition of MinusInfinity was here
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/2.3.0/json/common.rb:129: warning: already initialized constant JSON::UnparserError
/Users/opanmustopah/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/json-1.8.6/lib/json/common.rb:128: warning: previous definition of UnparserError was here
[2017-04-16 12:11:49] INFO  WEBrick 1.3.1
[2017-04-16 12:11:49] INFO  ruby 2.3.3 (2016-11-21) [x86_64-darwin15]
[2017-04-16 12:11:49] INFO  WEBrick::HTTPServer#start: pid=97591 port=2300
```

Do you guys have any idea how to remove these warnings?
Ruby version: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]`
Hanami version: `v1.0.0`

Thank you in advance

**Comment by mereghost** [comment]
These warnings are due to our code reloading feature, well... reloading the class definitions and it's constants and are innocuous.

That being said, we intend to perfect our code reloading so, among other things, it will not trigger any warnings.

**Comment by mereghost** [comment]
Also for getting your answers way faster, consider joining us at https://gitter.im/hanami/chat . =)

**Comment by jodosha** [comment]
@opan Why aren't you using json 2.1.0? Does `hanami server` causes these warnings too?

**Comment by diawl** [comment]
I got similar warnings but only for `hanami c`, `hanami server` does not cause them. Is there anyway to get rid of them for `hanami c`?

**Comment by rpanachi** [comment]
I have the same issue after upgrade from Hanami 0.9 to 1.0, either running `hanami c` or `hanami server`. When running server, the same "already initialized constant" warnings are shown on each request.

I can't leave the `lib/<project-file>.rb` empty (https://github.com/hanami/hanami/pull/762) because I explicitly require all dependences there (https://github.com/hanami/hanami/issues/758#issuecomment-291124476)

Even running with `--no-code-reloading` option (https://github.com/hanami/hanami/issues/775#issuecomment-297829296) cause this "warning dump".

The only working solution I find is to run `RUBYOPT="-W0" hanami server` but this could cause a lot of side effects.

Just to be clear, this cause ALL constants in lib dir, like class defined exceptions or enums, to be warned on each request. Any other solution or alternative? Any way to use the "old way" code reloading?

**Comment by cllns** [comment]
I think I had this problem and upgrading the `json` gem fixed it. Is there some reason you need an older version of `json`?

**Comment by opan** [comment]
@jodosha Sorry for the late response. Well those warnings is gone now after I uninstall the `json` gem and then run `bundle install`. Btw thank you very much for all response!

**Comment by jodosha** [comment]
@opan do you start the server with `hanami server` or prefixing it via `bundle exec hanami server`?

**Comment by opan** [comment]
@jodosha I start the server with `hanami server`, without `bundle exec`

**Comment by jodosha** [comment]
@opan 

Bundler guarantees that the ruby gems in your project are loaded only once, and the exact version that your `Gemfile` says to load. These warnings are caused by the double loading of the gems in your system. We assume you to use Bundler.

To solve this problem, you should use `bundle exec hanami server`. Or if you don't want to prefix the commands, you can use Bundler binstubs.

Run this command only once:

```shell
bundle binstubs hanami
```

It will create a `bin/hanami` file to use:

```shell
bin/hanami server
```

Both `bundle exec hanami server` and `bin/hanami server` will avoid these warnings.

**Comment by opan** [comment]
@jodosha Thank you for the `binstubs` command. I will try it
