### ISSUE TITLE
Generate modules in app namespace for custom load paths

### ISSUE THREAD

**Issue by sleekybadger** [hanami/hanami#776]
Hi, thank you for such great project.

I wonder, should we automatically generate modules that not defined for custom directories that we define in Application configuration block?

#### Example:

```
module Api
  class Application < Hanami::Application
    configure do
      ...
      load_paths << [
        'controllers',
        'views',
        'schemas'
      ]
      ...
    end
  end
end
```

For such config in addition to `Api::Controllers` and `Api::Views` we will generate `Api::Schemas` module.

I think that this can be handy, cause it will be help keep consistent directory structures and will remove need in empty modules definitions.

What do you all think about this? 💡

**Comment by mereghost** [comment]
Hmmm... I personally have no problem with it, even if it's a bit too magic and you can already create those by using pure ruby.

WDYT @hanami/core ?

**Comment by TiteiKo** [comment]
Nope for me. Even if you remove `'controllers'` from the list, `Api::Controllers` will still be generated because there's no relationship between loading directories and modules creation.

Furthermore, it won't remove empty modules definitions, you just won't see it ;)

And if you add `lib` to the loading, when in fact you put classes like `Api::DoTheStuff` in `apps/api/lib`, then you'd have created an empty `Api::Libs` module (without knowing it) for nothing :(

**Comment by jodosha** [comment]
@sleekybadger Hi and thanks for the proposal, but it's already happening at the boot of the project.

This feature is something that will be removed, (less magic yay! 🎉 ) in Hanami 2.0, where we'll generate actions like this:

```ruby
module Web
  module Controllers
    module Home
      class Index
        # ...
      end
    end
  end
end
```

This will create all the namespaces in the plain old Ruby way.
