### ISSUE TITLE
Run bundle using option after new project is created.

### ISSUE THREAD

**Issue by AlfonsoUceda** [hanami/hanami#857]
@citizen428 [proposed](https://github.com/hanami/hanami/issues/849#issuecomment-338906112) to run bundle after a new Hanami project is created.

**Comment by cllns** [comment]
I think we should run `bundle install` in the new folder by default. And have a `--skip-bundle-install`. What do you think?

**Comment by AlfonsoUceda** [comment]
I wouldn't do that because some people use gemsets, I think it's better to be conservative but I would like to hear more opinions.

**Comment by citizen428** [comment]
I'm with @AlfonsoUceda on this one, there shouldn't be too many assumptions regarding people's environments and preferences built in.

**Comment by jodosha** [comment]
Me and @cllns had a conversation about this. Probably it's not a good idea. People may want to fiddle with their `Gemfile` first. Or if they are newcomers, they may understand that Hanami is slow to generate a new project, but it's the wait for Rubygems instead.

As last thing, I'd defer this, because we're going probably to do more work on CLI hooks.

**Comment by AlfonsoUceda** [comment]
Closing this issue because I think bundler should be run manually.
