### ISSUE TITLE
Application middleware triggers before forceful redirect to SSL

### ISSUE THREAD

**Issue by spectator** [hanami/hanami#869]
Hi,

I have noticed interesting behavior of `force_ssl` option in production. When there is a custom middleware inserted into middleware stack it triggers before `force_ssl` takes place essentially allowing unencrypted traffic to hit it. Should't all middleware be behind SSL when this option is enabled?

Here is a simple app to demonstrate the issue https://github.com/spectator/hanami_force_ssl

Here is how it looks when `force_ssl` is not enabled

App with no middleware

```
curl -i http://localhost:5000/web
HTTP/1.1 200 OK 
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Content-Security-Policy: form-action 'self'; frame-ancestors 'self'; base-uri 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' https: data:; style-src 'self' 'unsafe-inline' https:; font-src 'self'; object-src 'none'; plugin-types application/pdf; child-src 'self'; frame-src 'self'; media-src 'self'
Content-Type: text/html; charset=utf-8
Content-Length: 21
Server: WEBrick/1.3.1 (Ruby/2.4.2/2017-09-14)
Date: Tue, 12 Dec 2017 00:10:54 GMT
Connection: Keep-Alive

hello from home/index%                                                                                                                                          
```

App with middleware

```
curl -i http://localhost:5000/api
HTTP/1.1 401 Unauthorized 
Content-Length: 12
Server: WEBrick/1.3.1 (Ruby/2.4.2/2017-09-14)
Date: Tue, 12 Dec 2017 00:10:48 GMT
Connection: Keep-Alive

Unauthorized%                                                                                                                                                   
```

Now the same with `force_ssl` enabled

App with no middleware

```
curl -i http://localhost:5000/web
HTTP/1.1 301 Moved Permanently 
Location: https://localhost:5000/web
Content-Length: 0
Server: WEBrick/1.3.1 (Ruby/2.4.2/2017-09-14)
Date: Tue, 12 Dec 2017 00:11:26 GMT
Connection: Keep-Alive
```

App with middleware

```
curl -i http://localhost:5000/api
HTTP/1.1 401 Unauthorized 
Content-Length: 12
Server: WEBrick/1.3.1 (Ruby/2.4.2/2017-09-14)
Date: Tue, 12 Dec 2017 00:11:22 GMT
Connection: Keep-Alive

Unauthorized%
```

Instead of redirect (like `/web` does) `/api` still returns what middleware returns.

Here is how middleware code looks (oversimplified version of what we have in production)

```
module App
  class AuthMiddleware
    def initialize(app)
      @app = app
    end

    def call(env)
      return [401, {}, ["Unauthorized"]]
      @app.call(env)
    end
  end
end
```

Hanami version 1.1.0

Is this intentional behavior or am I missing something?

**Comment by AlfonsoUceda** [comment]
Hi @spectator sorry for the late answer. Well this is because you are halting the middleware process before reaching the router, so that's why `force_ssl` won't work.

In my opinion, if you are using a middleware for authorisation and you might halt the execution in that middleware, you could use Apache or Nginx rule for ssl redirect.

cc @jodosha

**Comment by jodosha** [comment]
@spectator I'm sorry about this issue. @AlfonsoUceda is right: there is a design problem. The request hits the middleware stack first and then the router. Because the router is the last component that dispatches the request to the app.

Now, I'm doing a lot of research and experiments on how to simplify this part of Hanami, and I can tell that both `force_ssl` and application level middleware are complex mechanisms that are worth to be removed in 2.0.

To solve your problem, I suggest to delegate to Nginx this task, or to use a Rack middleware (eg. `rack-ssl`) in `config.ru` of your Hanami project.

**Comment by spectator** [comment]
Appreciate you for looking into this @jodosha and @AlfonsoUceda !

I did solve this with `rack-ssl` for systems where this was critical.
