### ISSUE TITLE
Consider adding `# frozen_string_literal: true` to generated files

### ISSUE THREAD

**Issue by graywolf** [hanami/hanami#879]
If hanami can work with it, it would be nice having `# frozen_string_literal: true` in generated files. What do you think?

**Comment by sandelius** [comment]
I always add it manually so I would be happy if it was already generated.

**Comment by davydovanton** [comment]
@graywolf great idea. Could you make a PR for this?

**Comment by graywolf** [comment]
sure, will give it a try

**Comment by cllns** [comment]
@graywolf Personally, I'd like this to be an option. For example: `hanami new bookshelf --frozen-string-literal`. And then other generators would have the same thing? (or maybe we can check some file and add it to the generated files if it exists in that one, maybe `config/environment.rb`?)

I'm sure you'd do it anyway, but it'd be great if this could have minimal diff noise. Find a few spots to add it, and test those, rather than running the full integration suite with and without frozen string literal. What do you think?

**Comment by graywolf** [comment]
@cllns In my opinion, when you /don't/ make in configurable and just force it to yes, it will imho simplify maintance going forward. Since you don't really have make sure it works with both configurations. And I'm running all my projects with manually added `frozen_string_literal: yes` and didn't see any issue caused by it (at least so far).

But I /can/ make it configurable (shouldn't be too hard), however even in that case I would suggest making it default option. One can always just make unfrozen string if really needed.

Checking one file (`config/environment.rb` or other) seems (at least to me) like too much magic and I'm against it... Even when documented, having option `--no-frozen-string-literal` in command help message is much easier to notice it's even an option.

Thoughts?

**Comment by cllns** [comment]
Thanks for opening the PR! 

I don't know if there's been other tests but one showed that [it's not even faster](http://ruby-performance-book.com/blog/2016/02/is-ruby-2-3-faster-frozen-string-literals-performance.html). If it were faster, and a better practice indisputably, I'd be all in favor of it. I'm just not sure if it is.

People can use frozen string literals throughout a Ruby project with:
```
RUBYOPT="--enable-frozen-string-literal" bundle exec hanami server # for example
```

If you use Rubocop, you can change your Hanami project manually:
``` 
bundle exec rubocop --auto-correct --only FrozenStringLiteralComment
```

What do you think about adding documentation to do either or both of these, instead of changing the generated files?

**Comment by sandelius** [comment]
It’s about memory allocation and not speed.

Skickat från min iPhone

**Comment by davydovanton** [comment]
@graywolf you can use another way. Rubocop can automatically add `frozen_string_literal: true` to all files without any manual work.

I agree that this line will be better but also if we will start working on an option for this (like in @cllns comment) we'll increase complication for all hanami/hanami code base. And in this case I prefer to use rubocop as a optional solution for this problem.

@cllns @sandelius WDYT? we can add information about rubocop or add rubocop as default dependency for all hanami projects (just put `gem "rubocop"` to Gemfile).

**Comment by davydovanton** [comment]
I love the idea with commented line in the gemfile! ❤️

**Comment by graywolf** [comment]
So to sum up: now I should modify generated app to pass rubocop out of the box?

**Comment by jodosha** [comment]
@graywolf I like the idea, we're going to that direction.

Unfortunately Hanami gems on 1.x aren't respecting that immutable strings. So this change would break apps.

This is the strategy:

  1. Port all the Hanami code base to use immutable strings. In this way the internals of the framework are forced to respect that directive, so they won't break apps.

  2. Generate new Hanami projects and code with that pragma comment.

  3. Make all the Hanami code and projects code to pass `rubocop` linters.

  4. New Hanami projects will **NOT** have `rubocop` in their `Gemfile`. If a dev wants to use it, she/he's free to do it and her/his project will be already passing the inspection.

But this is for 2.0, mainly because to respect immutable strings we need to change our API.
