### ISSUE TITLE
Respond with errors in JSON if MIME type is JSON

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#892]
If a user makes a bad request with JSON (either with `Accept` or `Content-Type`), the response is in HTML.

By default, it would be nice to respond with an error in JSON. Instead of rendering `500.html.erb`, it would be nice if the following JSON were returned instead:
```json
{"status":500, "text":"Internal Server Error"}
```
I'm not set on that response format, and I'm open to others. 

We should be flexible though, and let people change the JSON format for the error response. I don't think we should use anything fancy, just use a Ruby hash and call `.to_json` on it. There could be a setting that would take a block (or lambda) with the status code and name of the status code. Perhaps it could take `stacktrace` too, for 500s in development? 

For example:
```
json_error_format do |code, text, extra| 
  Hash[response: "Status #{ code }: #{ text } "]
end
# Would be: { "response": "Status 500: Internal Server Error" }
```

See #889 for context.

It could also be cool to [rescue `JSON::ParserError`, when the JSON is malformed](https://robots.thoughtbot.com/catching-json-parse-errors-with-custom-middleware), and provide a useful 400 error message.

What does everyone think about this? @hanami/core & others?

**Comment by AlfonsoUceda** [comment]
👍

**Comment by AlfonsoUceda** [comment]
@cllns it makes sense, but not only for JSON, even for other mime types like XML, I know we have a `default_response_format` configuration but it would be good to set by request.

**Comment by iJackUA** [comment]
What about instead of custom static error pages like `apps/web/templates/500.html.erb`
allow specifying in app configuration a dynamic action handler for each "standard error type" that is handled automatically by Hanami?
Like `/apps/api/application.rb`
```ruby
configure do
  custom_response_code_handlers do
    handle 500, 'errors#unknown'
    handle 404, 'error#not_found'
    ...
  end
end
```
That way you give a complete freedom for app developer to implement any kind of error repond and formatting. Also `exception` object should be accessible as a param in this action for custom representation.
But by default you can keep fallback to static html error pages. In any case there is not big sense to do any automatic response like `{"status":500, "text":"Internal Server Error"}` because each API would have it's own response body structure, error codes handling (eg to show code 500 or code 200, but specail app specific error code in response body etc.). So app developers in most cases would require to have a lot of control on error rendering (and custom logging/tracing).

Right now the only way for mass-handling for example 500 errors in API I found 
```ruby
module Api
  module Helpers
    def self.included(action)
      action.class_eval do
        handle_exception ::Exception => :render_unknown_exception
      end
    end

    def render_unknown_exception(exception)
      Hanami.logger.error(exception.message)
      render_error_json
    end
```
 
but I still can not handle 404 error for example as it is managed on router level

**Comment by jodosha** [comment]
Stale
