### ISSUE TITLE
Expect to improve server CLI usage

### ISSUE THREAD

**Issue by seasonxuan** [hanami/hanami#910]
When I run ```hanami server```, I can visit by ```http://localhost:2300```, but I **can't** visit by LAN IP address ```http://192.168.0.45:2300```
Similarly, when I run ```hanami server --host=192.168.0.45```, I can visit by LAN IP address, but I **can't** visit by localhost. 
Finally, when I run ```hanami server --host=0.0.0.0```, I can visit by both IP address and localhost.

I **expect** the last usage will be the default usage for ``hanami server```

Hanami Version:  V1.1.1

**Comment by cllns** [comment]
Thanks for this issue, but I think `localhost` is what we prefer, since it’s more secure. We want to be secure by default. 

Binding to `0.0.0.0` means your development web server will be available to anyone on your local network. This means that, at a coffee shop for example, if you’re using `hanami-webconsole`, anyone could run arbitrary commands on your computer. 😱

I think we should leave it as `localhost`, though there are definitely times when setting it to `0.0.0.0` makes sense. Maybe we could document this instead, so people can see how to do this, and also learn about the security vulnerabilities it introduces.

I’m going to close this but feel free to let me know if I got this wrong and I’ll open it back up. 🌸
